#!/usr/bin/env python

import sys
from Bio import Seq

if len(sys.argv) < 2:
    print('USAGE: generate_weights SCORES.txt')
    sys.exit(1)

print('\t'.join(('kmer', 'revcomp', 'weight')))

for l in open(sys.argv[1]):
    kmer, w = l.rstrip().split('\t') 
    print('\t'.join( (kmer, str(Seq.Seq(kmer).reverse_complement()), w) ))
